# Generated by Django 4.1.7 on 2023-04-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
